#seo
author: Mario Lanza
description: Dedicated to all the IHS graduates and staff who have passed away throughout the years.
facebook:
  publisher: https://www.facebook.com/ihsmemorial/
  admins: mariolanza
locale: en_US
logo: /assets/10609708_672957986115083_7627741849738825230_n.png
tagline: Dedicated to graduates and staff
title: Interlake High School Memorial Wall
twitter:
  username: MarioJLanza
url: "https://ihsmemorial.org"
social:
  name: Mario Lanza
  email: MLanza1974@aol.com
  links:
    - https://twitter.com/MarioJLanza
    - https://github.com/MarioMangler
    - https://www.facebook.com/mariolanza

#chirpy
avatar: /assets/10609708_672957986115083_7627741849738825230_n.png
baseurl: ""
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]
disqus:
  comments: true
  shortname: "interlake-high-school-memorial-wall"
github:
  username: MarioMangler
google_analytics:
  id: "UA-188003746-1"
  pv:
    enabled: false
img_cdn: ""
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options â€º https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
lang: en-US
sass:
  sass_dir: /assets/css
  style: compressed
theme: jekyll-theme-chirpy
theme_mode: dark
timezone: America/Los_Angeles
toc: true

#ihsmemorial
collections:
  tabs:
    output: true
    sort_by: order
  cause:
    output: true
    sort_by: title
defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      breadcrumb:
        - label: Home
          url: /
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: _tabs
    values:
      order: 99
  - scope:
      path: _cause
    values:
      layout: tag
      breadcrumb:
        - label: Home
          url: /
  - scope:
      path: index.html
    values:
      breadcrumb:
        - label: Home
exclude:
  - vendor
  - Gemfile.lock
  - Gemfile
  - docs
  - README.md
  - LICENSE
  - Rakefile
  - .tm_properties
include:
  - _headers
jekyll-archives:
  enabled: []
paginate: 25
permalink: /:categories/:title/
repository: Interlake-Saints/ihsmemorial.org
