backend:
  name: github
  repo: Interlake-Saints/ihsmemorial.org
  branch: main
collections:
  - name: 'deaths'
    label: 'Deaths'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'post'
      - label: 'Title'
        name: 'title'
        widget: 'string'
        hint: 'Name edits cannot be made through the CMS.'
      - label: 'Sort Key'
        name: 'sortKey'
        widget: 'string'
        hint: 'Typically LastName, FirstName so that class pages are sorted alphabetical by last name.'
      - label: 'Death Date'
        name: 'date'
        widget: 'datetime'
        format: 'YYYY-MM-DD'
        date_format: 'YYYY-MM-DD'
        time_format: false
        hint: 'In unknown, use the closest known date or 1900-01-01 if the date is totally unknown.'
      - label: 'Death Date Unknown'
        name: 'dateUnknown'
        widget: 'boolean'
        required: false
        hint: 'Mark true if the exact date is not known.'
      - label: 'Author'
        name: 'author'
        widget: 'string'
        required: false
        hint: 'Defaults to Mario Lanza if left blank.'
      - label: 'Categories'
        name: 'categories'
        widget: 'select'
        multiple: true
        options:
          - class-of-1969
          - class-of-1970
          - class-of-1971
          - class-of-1972
          - class-of-1973
          - class-of-1974
          - class-of-1975
          - class-of-1976
          - class-of-1977
          - class-of-1978
          - class-of-1979
          - class-of-1980
          - class-of-1981
          - class-of-1982
          - class-of-1983
          - class-of-1984
          - class-of-1985
          - class-of-1986
          - class-of-1987
          - class-of-1988
          - class-of-1989
          - class-of-1990
          - class-of-1991
          - class-of-1992
          - class-of-1993
          - class-of-1994
          - class-of-1995
          - class-of-1996
          - class-of-1997
          - class-of-1998
          - class-of-1999
          - class-of-2000
          - class-of-2001
          - class-of-2002
          - class-of-2003
          - class-of-2004
          - class-of-2005
          - class-of-2006
          - class-of-2007
          - class-of-2008
          - class-of-2009
          - class-of-2010
          - class-of-2011
          - class-of-2012
          - class-of-2013
          - class-of-2014
          - class-of-2015
          - class-of-2016
          - class-of-2017
          - class-of-2018
          - class-of-2019
          - staff
        hint: 'New classes cannot be created through the CMS.'
      - label: 'Cause of Death'
        name: 'tags'
        value_field: 'id'
        widget: 'relation'
        collection: 'causes'
        search_fields: [id]
        multiple: true
        required: false
      - label: 'Images'
        name: 'images'
        widget: 'list'
        required: false
      - label: 'Gender'
        name: 'gender'
        widget: 'select'
        options: ['female', 'male', 'other']
      - label: 'Obituary URL'
        name: 'obituary'
        widget: 'string'
        required: false
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
  - name: 'causes'
    label: 'Causes'
    folder: '_cause/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Layout'
        name: 'layout'
        widget: 'hidden'
        default: 'tag'
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Identifier'
        name: 'id'
        widget: 'string'
        hint: 'This is the id used in post causes.'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
media_folder: '/assets'
public_folder: "/assets"
site_url: https://ihsmemorial.org
